import 'dotenv/config';
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { PrismaClient, type User } from '@prisma/client';
import { buildApp } from '../services/api/src/app.js';
import { defaults, today, ensureMissions } from '../services/api/src/domain.js';
const url=process.env.DATABASE_URL||'';
if(!url || !new URL(url).pathname.startsWith('/demo_'))throw new Error('Integration tests require a dedicated demo_ database.');
const db=new PrismaClient();
const cfg={origin:'http://localhost:5173',googleClientId:'',bootstrapEmail:'',production:false,demo:false,databaseUrl:url};
const app=await buildApp(db,cfg);
let familyId:string,p1:User,p2:User,c1:User,c2:User,outsider:User;
const auth=new Map<string,{cookie:string;csrf:string}>();
async function makeUser(name:string,role:string,family:string|null=familyId){const u=await db.user.create({data:{googleSub:`test:${randomUUID()}`,email:`${randomUUID()}@example.test`,name,role,familyId:family}});const raw=randomBytes(32).toString('hex'),csrf=randomBytes(32).toString('hex');await db.session.create({data:{tokenHash:createHash('sha256').update(raw).digest('hex'),userId:u.id,csrf,expiresAt:new Date(Date.now()+600000)}});auth.set(u.id,{cookie:`family_session=${raw}`,csrf});return u;}
async function req(user:User,path:string,body?:unknown,method:'GET'|'POST'|'PATCH'|'DELETE'=body===undefined?'GET':'POST',extra:Record<string,string>={}){const a=auth.get(user.id)!;return app.inject({method,url:`/api${path}`,headers:{origin:cfg.origin,cookie:a.cookie,'x-csrf-token':a.csrf,...extra},...(body!==undefined?{payload:body}:{})});}
async function freshMission(child:User,status='SUBMITTED'){const t=await db.missionTemplate.create({data:{...defaults[0],familyId}});return db.mission.create({data:{familyId,userId:child.id,templateId:t.id,date:today(),title:'검증 미션',description:'test',dueTime:'23:59',reward:5,penalty:5,status}});}
before(async()=>{const f=await db.family.create({data:{name:'자동검증 전용'}});familyId=f.id;p1=await makeUser('부모1','PARENT');p2=await makeUser('부모2','PARENT');c1=await makeUser('아이1','CHILD');c2=await makeUser('아이2','CHILD');outsider=await makeUser('외부인','PARENT',null);for(const c of[c1,c2])await db.wallet.create({data:{userId:c.id,familyId,balance:100}});await app.ready();});
after(async()=>{await db.notification.deleteMany({where:{userId:{in:[...auth.keys()]}}});await db.session.deleteMany({where:{userId:{in:[...auth.keys()]}}});for(const table of ['auditLog','pointEntry','redemption','mission','missionTemplate','wallet','event','invitation'] as const)await (db[table] as any).deleteMany({where:{familyId}});await db.user.deleteMany({where:{id:{in:[...auth.keys()]}}});await db.family.deleteMany({where:{id:familyId}});await app.close();await db.$disconnect();});

test('unauthenticated access and unconfigured Google login are rejected',async()=>{assert.equal((await app.inject({method:'GET',url:'/api/dashboard'})).statusCode,401);assert.equal((await app.inject({method:'POST',url:'/api/auth/google',headers:{origin:cfg.origin},payload:{credential:'forged-token'}})).statusCode,503);});
test('demo login does not exist in normal mode',async()=>{assert.equal((await app.inject({method:'POST',url:'/api/demo/login',headers:{origin:cfg.origin},payload:{userId:p1.id}})).statusCode,404);});
test('production demo configuration is refused',async()=>{await assert.rejects(buildApp(db,{...cfg,demo:true,production:true}),/Demo requires/);});
test('cross-origin and missing CSRF mutations are rejected',async()=>{assert.equal((await req(p1,'/invitations',{email:'kid@example.test',name:'아이',role:'CHILD'},'POST',{origin:'https://attacker.example'})).statusCode,403);assert.equal((await req(p1,'/invitations',{email:'kid@example.test',name:'아이',role:'CHILD'},'POST',{'x-csrf-token':''})).statusCode,403);});
test('children cannot create parent invitations',async()=>{assert.equal((await req(c1,'/invitations',{email:'kid@example.test',name:'아이',role:'PARENT'})).statusCode,403);});
test('children cannot approve, even their own mission',async()=>{const m=await freshMission(c1);assert.equal((await req(c1,`/missions/${m.id}/review`,{version:0,decision:'SUCCEEDED'})).statusCode,403);});
test('duplicate generation keeps one occurrence per child/template/date',async()=>{await ensureMissions(db,familyId);const count=await db.mission.count({where:{familyId}});await ensureMissions(db,familyId);assert.equal(await db.mission.count({where:{familyId}}),count);});
test('child cannot submit a sibling mission',async()=>{const m=await freshMission(c2,'OPEN');assert.equal((await req(c1,`/missions/${m.id}/submit`,{version:0})).statusCode,404);});
test('double submission sends one notification per parent',async()=>{const m=await freshMission(c1,'OPEN');const results=await Promise.all([req(c1,`/missions/${m.id}/submit`,{version:0}),req(c1,`/missions/${m.id}/submit`,{version:0})]);assert.ok(results.every(r=>[200,409].includes(r.statusCode)));assert.equal(await db.notification.count({where:{userId:{in:[p1.id,p2.id]},title:{contains:'검증 미션 완료 확인'}}}),2);});
test('simultaneous approvals credit the wallet exactly once',async()=>{const m=await freshMission(c1);const before=(await db.wallet.findUniqueOrThrow({where:{userId:c1.id}})).balance;const results=await Promise.all([req(p1,`/missions/${m.id}/review`,{version:0,decision:'SUCCEEDED'}),req(p2,`/missions/${m.id}/review`,{version:0,decision:'SUCCEEDED'})]);assert.ok(results.every(r=>[200,409].includes(r.statusCode)));assert.equal(await db.pointEntry.count({where:{sourceKey:`mission:${m.id}`}}),1);assert.equal((await db.wallet.findUniqueOrThrow({where:{userId:c1.id}})).balance,before+5);});
test('exceptions create no ledger entry; failure is a single debit',async()=>{const m=await freshMission(c1,'EXCEPTION_PENDING');assert.equal((await req(p1,`/missions/${m.id}/review`,{version:0,decision:'EXEMPT',note:'사전 승인된 병원 일정'})).statusCode,200);assert.equal(await db.pointEntry.count({where:{sourceKey:`mission:${m.id}`}}),0);const f=await freshMission(c1,'OPEN');assert.equal((await req(p1,`/missions/${f.id}/review`,{version:0,decision:'FAILED',note:'가족 확인'})).statusCode,200);assert.equal((await db.pointEntry.findUniqueOrThrow({where:{sourceKey:`mission:${f.id}`}})).points,-5);});
test('concurrent withdrawals cannot overspend; cancellation releases the hold',async()=>{await db.wallet.update({where:{userId:c2.id},data:{balance:100,held:0}});const results=await Promise.all([req(c2,'/redemptions',{points:80},'POST',{'idempotency-key':randomUUID()}),req(c2,'/redemptions',{points:80},'POST',{'idempotency-key':randomUUID()})]);assert.deepEqual(results.map(r=>r.statusCode).sort(),[200,422]);const r=results.find(r=>r.statusCode===200)!.json();assert.equal((await db.wallet.findUniqueOrThrow({where:{userId:c2.id}})).held,80);assert.equal((await req(c2,`/redemptions/${r.id}/cancel`,{})).statusCode,200);assert.equal((await db.wallet.findUniqueOrThrow({where:{userId:c2.id}})).held,0);});
test('withdrawal retries are idempotent; changing payload is a conflict',async()=>{const key=randomUUID();const a=await req(c2,'/redemptions',{points:10},'POST',{'idempotency-key':key});const b=await req(c2,'/redemptions',{points:10},'POST',{'idempotency-key':key});assert.equal(a.json().id,b.json().id);assert.equal((await req(c2,'/redemptions',{points:11},'POST',{'idempotency-key':key})).statusCode,409);await req(c2,`/redemptions/${a.json().id}/cancel`,{});});
test('payment has one owner and repeated completion debits once',async()=>{const r=(await req(c2,'/redemptions',{points:20},'POST',{'idempotency-key':randomUUID()})).json();assert.equal((await req(p1,`/redemptions/${r.id}/approve`,{})).statusCode,200);assert.equal((await req(p1,`/redemptions/${r.id}/start-payment`,{})).statusCode,200);assert.equal((await req(p2,`/redemptions/${r.id}/start-payment`,{})).statusCode,409);assert.equal((await req(p2,`/redemptions/${r.id}/mark-paid`,{})).statusCode,403);const before=(await db.wallet.findUniqueOrThrow({where:{userId:c2.id}})).balance;await req(p1,`/redemptions/${r.id}/mark-paid`,{});await req(p1,`/redemptions/${r.id}/mark-paid`,{});assert.equal((await db.wallet.findUniqueOrThrow({where:{userId:c2.id}})).balance,before-20);assert.equal(await db.pointEntry.count({where:{sourceKey:`payout:${r.id}`}}),1);});
test('balance loss after request prevents starting payment',async()=>{const r=(await req(c2,'/redemptions',{points:40},'POST',{'idempotency-key':randomUUID()})).json();await req(p1,`/redemptions/${r.id}/approve`,{});await db.wallet.update({where:{userId:c2.id},data:{balance:0}});assert.equal((await req(p1,`/redemptions/${r.id}/start-payment`,{})).statusCode,409);await req(c2,`/redemptions/${r.id}/cancel`,{});});
test('dashboard excludes sibling wallets and ledger for children',async()=>{const r=await req(c1,'/dashboard');assert.equal(r.statusCode,200);assert.ok(r.json().wallets.every((w:any)=>w.userId===c1.id));assert.ok(r.json().entries.every((w:any)=>w.userId===c1.id));assert.equal(r.json().templates.length,0);});
test('unassigned users cannot bootstrap without configured parent email',async()=>{assert.equal((await req(outsider,'/families',{name:'무단 가족'})).statusCode,403);});
test('invitation is account-bound and can only be consumed once',async()=>{const raw=(await req(p1,'/invitations',{email:outsider.email,name:'새 가족',role:'PARENT'})).json().token;const impostor=await makeUser('다른 사람','UNASSIGNED',null);assert.equal((await req(impostor,'/invitations/accept',{token:raw})).statusCode,403);assert.equal((await req(outsider,'/invitations/accept',{token:raw})).statusCode,200);assert.equal((await req(outsider,'/invitations/accept',{token:raw})).statusCode,409);});
test('events validate dates and child ownership',async()=>{const key=randomUUID();assert.equal((await req(c1,'/events',{title:'잘못된 날짜',date:'2026-02-31',time:'12:00',kind:'EVENT'},'POST',{'idempotency-key':key})).statusCode,422);const r=await req(c1,'/events',{title:'학원',date:today(),time:'15:00',kind:'EVENT',note:'교재'},'POST',{'idempotency-key':randomUUID()});assert.equal(r.statusCode,200);assert.equal((await req(c2,`/events/${r.json().id}`,undefined,'DELETE')).statusCode,404);assert.equal((await req(p1,`/events/${r.json().id}`,undefined,'DELETE')).statusCode,200);});

test('exception requests notify parents and stay pending without points',async()=>{const m=await freshMission(c1,'OPEN');assert.equal((await req(c1,`/missions/${m.id}/exception`,{version:0,note:'가족과 사전 협의'})).statusCode,200);assert.equal((await db.mission.findUniqueOrThrow({where:{id:m.id}})).status,'EXCEPTION_PENDING');assert.equal(await db.notification.count({where:{userId:{in:[p1.id,p2.id]},title:'아이1 · 미션 예외 신청'}}),2);assert.equal(await db.pointEntry.count({where:{sourceKey:`mission:${m.id}`}}),0);});
test('past unresolved missions remain available to parents',async()=>{const m=await freshMission(c1,'OPEN');await db.mission.update({where:{id:m.id},data:{date:'2026-01-01'}});const d=(await req(p1,'/dashboard')).json();assert.ok(d.missions.some((x:any)=>x.id===m.id));});
