<script setup lang="ts">
import GoogleCalendarPanel from './components/GoogleCalendarPanel.vue';
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { House, CalendarDays, Wallet as WalletIcon, Bell, Settings2, Check, ChevronRight, ChevronLeft, Plus, LogOut, ShieldCheck, CircleCheck, Clock3, ArrowUpRight, ArrowDownLeft, X, Users, Sparkles, ListChecks } from 'lucide-vue-next';
import { state, api, me, load, action, type User, type Mission, type Redemption } from './api';
const route=useRoute(),router=useRouter();
const parent=computed(()=>state.user?.role==='PARENT');
const path=computed(()=>route.path);
const isAdmin=computed(()=>path.value.startsWith('/admin'));
const names=computed(()=>Object.fromEntries((state.data?.members||[]).map(m=>[m.id,m.name])));
const demoUsers=ref<User[]>([]),clientId=ref(''),nonce=ref(''),loginLoading=ref(false),busy=ref(false);
const modalRef=ref<HTMLDialogElement|null>(null);
const selectedChild=ref('all'),dialog=ref(''),selectedMission=ref<Mission|null>(null),reason=ref('');
const formTitle=ref(''),formNote=ref(''),formDate=ref(''),formTime=ref('15:00'),eventKind=ref('EVENT');
const inviteName=ref(''),inviteEmail=ref(''),inviteRole=ref('CHILD'),inviteToken=ref(''),acceptToken=ref(''),familyName=ref('우리집');
const points=ref(10),reward=ref(5),penalty=ref(5),weekdays=ref('1,2,3,4,5'),requestKey=ref(crypto.randomUUID());
const wallet=computed(()=>state.data?.wallets.find(w=>w.userId===state.user?.id));
const available=computed(()=>Math.max(0,(wallet.value?.balance||0)-(wallet.value?.held||0)));
const missions=computed(()=> (state.data?.missions||[]).filter(m=>m.date===state.data?.today&&(selectedChild.value==='all'||m.userId===selectedChild.value)));
const pending=computed(()=> (state.data?.missions||[]).filter(m=>['SUBMITTED','EXCEPTION_PENDING'].includes(m.status)));
const completed=computed(()=>missions.value.filter(m=>m.status==='SUCCEEDED').length);
const unread=computed(()=>state.data?.notifications.filter(n=>!n.readAt).length||0);
const children=computed(()=>state.data?.members.filter(m=>m.role==='CHILD')||[]);
const dateLabel=computed(()=>new Date(`${state.data?.today||'2026-01-01'}T12:00:00+09:00`).toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'long'}));
const statusLabel:Record<string,string>={OPEN:'아직 남았어요',SUBMITTED:'부모 확인 중',SUCCEEDED:'완료했어요',FAILED:'미수행',EXCEPTION_PENDING:'예외 확인 중',EXEMPT:'오늘은 쉬어요',REQUESTED:'신청 대기',APPROVED:'지급 승인',PAYING:'지급 중',PAID:'지급 완료',CANCELLED:'취소',REJECTED:'거절'};
const title=computed(()=>({'/today':parent.value?'가족의 오늘':'나의 오늘','/calendar':'가족 달력','/wallet':'포인트 지갑','/notifications':'알림함','/settings':'우리 가족','/admin':'관리 대시보드','/admin/reviews':'미션 확인','/admin/missions':'반복 미션','/admin/payments':'용돈 정산'}[path.value]||'나의 오늘'));
const nav=[{to:'/today',text:'오늘',icon:House},{to:'/calendar',text:'가족 달력',icon:CalendarDays},{to:'/wallet',text:'포인트',icon:WalletIcon},{to:'/settings',text:'우리 가족',icon:Users}];
const adminNav=[{to:'/admin/reviews',text:'미션 확인',icon:CircleCheck},{to:'/admin/missions',text:'반복 미션',icon:ListChecks},{to:'/admin/payments',text:'용돈 정산',icon:WalletIcon}];
const month=ref(new Date().getMonth()),year=ref(new Date().getFullYear());
const calendarCells=computed(()=>{const start=new Date(year.value,month.value,1).getDay(),days=new Date(year.value,month.value+1,0).getDate();return [...Array(start).fill(0),...Array.from({length:days},(_,i)=>i+1)];});
const dateFor=(d:number)=>`${year.value}-${String(month.value+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
const eventsFor=(date:string)=>(state.data?.events||[]).filter(e=>e.kind==='ANNIVERSARY'?e.date.slice(5)===date.slice(5):(e.date<=date&&(e.endDate||e.date)>=date));
const monthEvents=computed(()=> (state.data?.events||[]).filter(e=>e.kind==='ANNIVERSARY'?Number(e.date.slice(5,7))===month.value+1:(e.date<=dateFor(new Date(year.value,month.value+1,0).getDate())&&(e.endDate||e.date)>=dateFor(1))).sort((a,b)=>a.date.slice(5).localeCompare(b.date.slice(5))));
function changeMonth(delta:number){const d=new Date(year.value,month.value+delta,1);year.value=d.getFullYear();month.value=d.getMonth();}
function open(kind:string,m?:Mission){state.error='';dialog.value=kind;selectedMission.value=m||null;reason.value='';formTitle.value='';formNote.value='';formDate.value=state.data?.today||'';formTime.value='15:00';requestKey.value=crypto.randomUUID();inviteToken.value='';}
async function run(fn:()=>Promise<unknown>,msg:string,close=false){if(busy.value)return;busy.value=true;let ok=false;await action(async()=>{await fn();ok=true;},msg);if(ok&&close)dialog.value='';busy.value=false;}
async function submit(m:Mission){await run(()=>api(`/missions/${m.id}/submit`,'POST',{version:m.version}),'완료를 제출했어요. 부모님 확인을 기다려 주세요.');}
async function decide(m:Mission,decision:string,note=''){await run(()=>api(`/missions/${m.id}/review`,'POST',{version:m.version,decision,note}),'미션 결과를 반영했습니다.',true);}
async function payout(r:Redemption,act:string){if(act==='mark-paid'&&!window.confirm(`${names.value[r.userId]}에게 ${(r.points*r.rate).toLocaleString()}원을 실제로 지급했나요?`))return;await run(()=>api(`/redemptions/${r.id}/${act}`,'POST',{}),'처리 결과를 반영했습니다.');}
async function save(){
 if(dialog.value==='exception'&&selectedMission.value)return run(()=>api(`/missions/${selectedMission.value!.id}/exception`,'POST',{note:reason.value,version:selectedMission.value!.version}),'예외를 신청했어요.',true);
 if(['FAILED','EXEMPT'].includes(dialog.value)&&selectedMission.value)return decide(selectedMission.value,dialog.value,reason.value);
 if(dialog.value==='withdraw')return run(()=>api('/redemptions','POST',{points:points.value},requestKey.value),'용돈을 신청했어요.',true);
 if(dialog.value==='event')return run(()=>api('/events','POST',{title:formTitle.value,date:formDate.value,time:formTime.value,kind:eventKind.value,note:formNote.value},requestKey.value),'일정을 추가했습니다.',true);
 if(dialog.value==='template')return run(()=>api('/templates','POST',{title:formTitle.value,description:formNote.value,weekdays:weekdays.value,dueTime:formTime.value,reward:reward.value,penalty:penalty.value}),'반복 미션을 추가했습니다.',true);
 if(dialog.value==='invite')return run(async()=>{const r=await api<{token:string}>('/invitations','POST',{name:inviteName.value,email:inviteEmail.value,role:inviteRole.value});inviteToken.value=r.token;},'초대 코드를 만들었습니다.');
}
async function demoLogin(id:string){await run(async()=>{const r=await api<{user:User;csrf:string}>('/demo/login','POST',{userId:id});state.user=r.user;state.csrf=r.csrf;selectedChild.value='all';await router.push('/today');},'시험 계정을 변경했습니다.');}
async function logout(){await run(async()=>{await api('/logout','POST',{});state.user=null;state.data=null;state.csrf='';await initLogin();},'로그아웃했습니다.');}
declare global { interface Window { google?:{accounts:{id:{initialize:(o:Record<string,unknown>)=>void;renderButton:(el:HTMLElement,o:Record<string,unknown>)=>void}}}; } }
async function renderGoogle(){await nextTick();const el=document.getElementById('google-button');if(!el||!window.google||!clientId.value)return;window.google.accounts.id.initialize({client_id:clientId.value,nonce:nonce.value,callback:async(r:{credential:string})=>{loginLoading.value=true;state.error='';try{const result=await api<{user:User;csrf:string}>('/auth/google','POST',r);state.user=result.user;state.csrf=result.csrf;await me();await router.push('/today');}catch(e){state.error=(e as Error).message;await initLogin();}finally{loginLoading.value=false;}}});window.google.accounts.id.renderButton(el,{theme:'outline',size:'large',width:280,text:'signin_with',locale:'ko'});}
async function initLogin(){const conf=await api<{clientId:string;nonce:string;demo:boolean}>('/auth/config');clientId.value=conf.clientId;nonce.value=conf.nonce;state.demo=conf.demo;if(conf.demo)demoUsers.value=await api<User[]>('/demo/users');if(clientId.value){if(window.google)await renderGoogle();else if(!document.getElementById('google-sdk')){const script=document.createElement('script');script.id='google-sdk';script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=renderGoogle;script.onerror=()=>{state.error='Google 로그인 화면을 불러오지 못했습니다. 새로고침해 주세요.';};document.head.append(script);}}}
let refreshTimer:ReturnType<typeof setInterval>;
onMounted(async()=>{try{try{await me();}catch(e){if(state.user)throw e;}await initLogin();if(route.path==='/')await router.replace('/today');}catch(e){state.error=(e as Error).message;}finally{state.loading=false;await renderGoogle();}refreshTimer=setInterval(()=>{if(state.user?.familyId&&document.visibilityState==='visible'&&!busy.value)load().catch(()=>{});},30000);});
onUnmounted(()=>clearInterval(refreshTimer));
watch(()=>route.path,()=>{state.error='';});
watch(dialog,async(value)=>{if(value){await nextTick();modalRef.value?.showModal();}});
</script>

<template>
<div v-if="state.loading" class="loading-screen"><div class="brand-mark"><House :size="30" /></div><p>우리집을 여는 중이에요.</p></div>
<div v-else-if="!state.user" class="login-page">
 <div class="login-art"><div class="brand"><span class="brand-mark"><House :size="27"/></span>우리집<span class="brand-en">OUR HOME</span></div><div><p class="eyebrow">가족의 하루, 함께</p><h1>작은 약속이<br>쌓이는 우리집.</h1><p>오늘의 할 일부터 함께하는 일정까지.<br>각자의 하루를 함께 챙겨요.</p><div class="sample-task"><CircleCheck/><span>오늘 할 일 마무리</span><strong>+10P</strong></div></div><small>우리 가족만의 공간</small></div>
 <section class="login-card"><span class="eyebrow">WELCOME HOME</span><h2>우리집에 들어가기</h2><p>가족에게 초대받은 Google 계정으로 로그인해 주세요.</p><div id="google-button"></div><p v-if="loginLoading">계정을 확인하고 있어요.</p><p v-if="!clientId" class="notice">Google 로그인 연결을 준비 중입니다.</p><div v-if="state.demo" class="demo-login"><span class="badge">시험용 공간 · 실제 잔액 아님</span><h3>가족 화면 둘러보기</h3><div class="demo-grid"><button v-for="u in demoUsers" :key="u.id" :disabled="busy" @click="demoLogin(u.id)"><span class="avatar">{{u.name.slice(0,1)}}</span>{{u.name}}<small>{{u.role==='PARENT'?'부모':'아이'}}</small></button></div></div><p v-if="state.error" role="alert" class="error">{{state.error}}</p></section>
</div>
<div v-else-if="!state.user.familyId" class="onboarding"><div class="brand-mark"><House/></div><h1>{{state.user.name}}님, 반가워요.</h1><p>초대받은 가족에 연결해 주세요.</p><form @submit.prevent="run(async()=>{await api('/invitations/accept','POST',{token:acceptToken.trim()});await me();},'가족에 연결되었습니다.')"><label>가족 초대 코드<input v-model="acceptToken" required autocomplete="off"></label><button class="primary" :disabled="busy">초대 수락</button></form><form v-if="state.canBootstrap" @submit.prevent="run(async()=>{await api('/families','POST',{name:familyName});await me();},'가족을 만들었습니다.')"><label>새 가족 이름<input v-model="familyName" required maxlength="80"></label><button class="secondary" :disabled="busy">우리 가족 만들기</button></form><p class="error" v-if="state.error" role="alert">{{state.error}}</p><button class="text-button" @click="logout">다른 계정으로 로그인</button></div>
<div v-else class="app-shell">
 <aside class="sidebar"><RouterLink to="/today" class="brand"><span class="brand-mark"><House :size="26"/></span>우리집</RouterLink><p class="sidebar-label">FAMILY SPACE</p><nav><RouterLink v-for="n in nav" :key="n.to" :to="n.to" :class="{active:path===n.to}"><component :is="n.icon" :size="21"/>{{n.text}}</RouterLink></nav><template v-if="parent"><p class="sidebar-label">부모 관리</p><nav><RouterLink v-for="n in adminNav" :key="n.to" :to="n.to" :class="{active:path===n.to}"><component :is="n.icon" :size="20"/>{{n.text}}<span v-if="n.to==='/admin/reviews'&&pending.length" class="count">{{pending.length}}</span></RouterLink></nav></template><div class="sidebar-bottom"><div class="family-note"><Users :size="22"/><strong>함께 채우는 하루</strong><p>작은 실천도 차곡차곡.</p></div><button class="account" @click="router.push('/settings')"><span class="avatar">{{state.user.name.slice(0,1)}}</span><span><strong>{{state.user.name}}</strong><small>{{parent?'부모 계정':'나의 공간'}}</small></span><Settings2 :size="18"/></button></div></aside>
 <main class="main-area"><header class="topbar"><span>{{state.data?.family.name||'우리 가족'}} <span class="topbar-divider">/</span> {{title}}</span><div><span v-if="state.demo" class="badge demo-badge">시험 데이터</span><button class="icon-button" aria-label="알림함" @click="router.push('/notifications')"><Bell :size="21"/><i v-if="unread" class="notification-dot"></i></button></div></header>
 <div v-if="state.error" class="error error-banner" role="alert">{{state.error}}<button aria-label="닫기" @click="state.error=''"><X :size="18"/></button></div>
 <nav v-if="parent&&isAdmin" class="mobile-admin-nav" aria-label="부모 관리 메뉴"><RouterLink v-for="n in adminNav" :key="n.to" :to="n.to" :class="{active:path===n.to}">{{n.text}}</RouterLink></nav>
 <div class="page-content" v-if="state.data">
  <template v-if="path==='/today'||path==='/admin'||(!['/calendar','/wallet','/settings','/notifications'].includes(path)&&!isAdmin)">
   <div class="page-heading"><div><p class="eyebrow">{{dateLabel}}</p><h1>{{parent?'우리 가족, 오늘은 어때요?':`${state.user.name}의 하루를 응원해!`}}</h1><p class="muted">{{parent?'아이들의 작은 실천을 확인해 주세요.':'하나씩 해내고, 나만의 포인트를 모아봐요.'}}</p></div><span class="day-symbol"><Sparkles :size="32"/></span></div>
   <div class="overview-grid"><section class="balance-card"><span>{{parent?'아이들이 모은 포인트':'내가 모은 포인트'}}</span><div class="big-number">{{(parent?state.data.wallets.reduce((s,w)=>s+w.balance,0):wallet?.balance||0).toLocaleString()}}<small>P</small></div><div class="balance-footer"><span>1P = 100원</span><RouterLink to="/wallet">지갑 보기 <ArrowUpRight :size="17"/></RouterLink></div></section><section class="progress-card"><div class="section-title"><span>오늘의 작은 성취</span><CircleCheck :size="22"/></div><div class="progress-numbers"><strong>{{completed}}</strong><span>/ {{missions.length}}개 완료</span></div><div class="progress-track"><div :style="{width:`${missions.length?completed/missions.length*100:0}%`}"></div></div><p>{{pending.length?'확인을 기다리는 미션이 있어요.':'오늘도 하나씩, 내 속도로.'}}</p></section></div>
   <div class="content-columns"><section><div class="section-heading"><h2>오늘의 미션 <span>{{missions.length}}</span></h2><select v-if="parent" v-model="selectedChild" aria-label="아이 선택"><option value="all">아이 전체</option><option v-for="k in children" :value="k.id">{{k.name}}</option></select><span v-else class="subtle-label">매일의 약속</span></div><div class="mission-list"><article v-for="m in missions" :key="m.id" class="mission-card" :class="{done:m.status==='SUCCEEDED'}"><div class="mission-symbol" :class="m.status.toLowerCase()"><CircleCheck v-if="m.status==='SUCCEEDED'"/><Clock3 v-else-if="m.status==='SUBMITTED'"/><Check v-else/></div><div class="mission-info"><div class="mission-meta"><span>{{m.dueTime}}까지</span><span v-if="parent">{{names[m.userId]}}</span></div><h3>{{m.title}}</h3><p>{{m.description}}</p><span class="status" :class="m.status.toLowerCase()">{{statusLabel[m.status]}}</span><small class="penalty-label">미수행 확정 시 −{{m.penalty}}P</small></div><div class="mission-side"><strong>+{{m.reward}}P</strong><button v-if="!parent&&m.status==='OPEN'" class="primary small" :disabled="busy" @click="submit(m)">완료하기</button><button v-if="!parent&&m.status==='OPEN'" class="text-button small" @click="open('exception',m)">예외 신청</button><button v-if="parent&&m.status==='SUBMITTED'" class="primary small" :disabled="busy" @click="decide(m,'SUCCEEDED')">승인</button></div></article><div v-if="!missions.length" class="empty"><ListChecks/><h3>아직 등록된 미션이 없어요.</h3><p>{{parent?'가족을 초대하고 반복 미션을 등록해 주세요.':'부모님이 미션을 등록하면 여기에 표시돼요.'}}</p></div></div></section><aside class="right-column"><section class="side-card"><div class="section-heading"><h2>오늘 함께할 일정</h2><RouterLink to="/calendar" aria-label="달력 보기"><ChevronRight :size="20"/></RouterLink></div><article v-for="e in eventsFor(state.data.today)" :key="e.id" class="agenda-item"><span class="agenda-line"></span><div><small>{{e.kind==='ANNIVERSARY'?'기념일':e.allDay?'종일':e.time}}</small><h3>{{e.title}}</h3><p>{{e.note}}</p></div></article><p v-if="!eventsFor(state.data.today).length" class="muted">오늘은 등록된 일정이 없어요.</p></section><section class="side-card weekly-note"><span class="eyebrow">SUNDAY TOGETHER</span><h2>일요일은 가족회의</h2><p>한 주의 미션을 돌아보고<br>모은 포인트를 용돈으로 바꿔요.</p><RouterLink :to="parent?'/admin/payments':'/wallet'">{{parent?'용돈 신청 확인':'내 포인트 확인'}} <ArrowUpRight :size="17"/></RouterLink></section></aside></div>
  </template>
  <template v-else-if="path==='/calendar'"><div class="page-heading"><div><p class="eyebrow">OUR SCHEDULE</p><h1>함께하는 날짜들</h1><p class="muted">가족 일정과 소중한 기념일을 모아봐요.</p></div><button class="primary" @click="open('event')"><Plus :size="18"/>일정 추가</button></div><GoogleCalendarPanel v-if="parent"/><section class="calendar-card"><div class="calendar-header"><h2>{{year}}년 {{month+1}}월</h2><div><button class="icon-button" aria-label="이전 달" @click="changeMonth(-1)"><ChevronLeft/></button><button class="icon-button" aria-label="다음 달" @click="changeMonth(1)"><ChevronRight/></button></div></div><div class="calendar-grid"><div v-for="d in ['일','월','화','수','목','금','토']" class="weekday">{{d}}</div><div v-for="(d,i) in calendarCells" :key="i" class="calendar-day" :class="{today:d&&dateFor(d)===state.data.today,blank:!d}"><span v-if="d" class="date-number">{{d}}</span><template v-if="d"><span v-for="e in eventsFor(dateFor(d))" class="event-chip" :class="{anniversary:e.kind==='ANNIVERSARY'}">{{e.title}}</span></template></div></div></section><div class="section-heading"><h2>이번 달 일정</h2></div><section class="list-panel"><article v-for="e in monthEvents" :key="e.id" class="list-row"><span class="date-tile">{{Number(e.date.slice(8))}}<small>{{month+1}}월</small></span><div class="grow"><h3>{{e.title}} <span v-if="e.source==='GOOGLE'" class="badge">Google</span> <span v-if="e.kind==='ANNIVERSARY'" class="badge">매년 기념일</span></h3><p>{{e.allDay?'종일':e.time}} · {{e.note||'함께 기억해요.'}}</p></div><a v-if="e.source==='GOOGLE'&&e.htmlLink" :href="e.htmlLink" target="_blank" rel="noopener noreferrer" class="text-button">Google에서 보기</a><button v-if="e.source!=='GOOGLE'&&(parent||e.ownerId===state.user.id)" class="text-button" @click="run(()=>api(`/events/${e.id}`,'DELETE'),'일정을 삭제했습니다.')">삭제</button></article><div v-if="!monthEvents.length" class="empty">이번 달에 함께할 일정을 추가해 보세요.</div></section></template>
  <template v-else-if="path==='/wallet'"><div class="page-heading"><div><p class="eyebrow">SMALL STEPS, BIG REWARDS</p><h1>차곡차곡 모은 포인트</h1><p class="muted">내가 해낸 일들이 용돈이 돼요.</p></div></div><div class="wallet-grid"><section v-for="w in state.data.wallets" :key="w.userId" class="balance-card"><span>{{names[w.userId]}}의 지갑</span><div class="big-number">{{w.balance.toLocaleString()}}<small>P</small></div><p>인출 가능 {{(Math.max(0,w.balance-w.held)*100).toLocaleString()}}원 · 신청 중 {{w.held}}P</p><button v-if="!parent" class="light-button" :disabled="available<1" @click="points=Math.min(10,available);open('withdraw')">용돈으로 바꾸기 <ArrowUpRight :size="18"/></button></section><div v-if="!state.data.wallets.length" class="empty">아이가 가족 초대를 수락하면 지갑이 만들어져요.</div></div><div class="section-heading"><h2>포인트 내역</h2><span class="muted">최근 100건</span></div><section class="list-panel"><article v-for="e in state.data.entries" :key="e.id" class="list-row"><div class="round-icon" :class="{negative:e.points<0}"><ArrowDownLeft v-if="e.points>0"/><ArrowUpRight v-else/></div><div class="grow"><h3>{{e.title}}</h3><p>{{parent?names[e.userId]+' · ':''}}{{new Date(e.createdAt).toLocaleDateString('ko-KR')}}</p></div><strong class="entry-points" :class="{negative:e.points<0}">{{e.points>0?'+':''}}{{e.points}}P</strong></article><div v-if="!state.data.entries.length" class="empty">완료 승인 후 적립 내역이 여기에 표시돼요.</div></section><div class="section-heading"><h2>용돈 신청 내역</h2></div><section class="list-panel"><article v-for="r in state.data.redemptions" :key="r.id" class="list-row"><div class="grow"><h3>{{(r.points*r.rate).toLocaleString()}}원 <span class="status">{{statusLabel[r.status]}}</span></h3><p>{{names[r.userId]}} · {{r.points}}P</p></div><button v-if="r.userId===state.user.id&&['REQUESTED','APPROVED'].includes(r.status)" class="text-button" :disabled="busy" @click="payout(r,'cancel')">신청 취소</button></article><div v-if="!state.data.redemptions.length" class="empty">아직 용돈 신청이 없어요.</div></section></template>
  <template v-else-if="path==='/notifications'"><div class="page-heading"><div><p class="eyebrow">UPDATES</p><h1>가족에게 온 소식</h1></div></div><section class="list-panel"><button v-for="n in state.data.notifications" :key="n.id" class="list-row notification-row" :class="{unread:!n.readAt}" @click="run(async()=>{await api(`/notifications/${n.id}/read`,'POST',{});await router.push(n.link);},'알림을 확인했습니다.')"><Bell/><div class="grow"><h3>{{n.title}}</h3><p>{{new Date(n.createdAt).toLocaleString('ko-KR')}}</p></div><ChevronRight/></button><div v-if="!state.data.notifications.length" class="empty">새 소식이 오면 알려드릴게요.</div></section></template>
  <template v-else-if="path==='/settings'"><div class="page-heading"><div><p class="eyebrow">OUR PEOPLE</p><h1>우리 가족</h1><p class="muted">각자의 하루를 함께 챙기는 사람들.</p></div><button v-if="parent" class="primary" @click="open('invite')"><Plus :size="18"/>가족 초대</button></div><section class="list-panel"><div v-for="m in state.data.members" :key="m.id" class="list-row"><span class="avatar large">{{m.name.slice(0,1)}}</span><div class="grow"><h3>{{m.name}}</h3><p>{{m.role==='PARENT'?'부모 · 승인과 가족 관리':'아이 · 미션과 포인트'}}</p></div><span v-if="m.id===state.user.id" class="badge">나</span></div></section><section class="settings-card"><h2>로그인 계정</h2><p>{{state.user.email}}</p><button class="secondary" @click="logout"><LogOut :size="17"/>로그아웃</button></section><section v-if="state.demo" class="settings-card"><span class="badge">시험용 공간</span><h2>다른 가족의 화면 보기</h2><p>별도 시험 DB를 사용하며 실제 잔액이 아닙니다.</p><div class="button-row"><button v-for="u in demoUsers" :disabled="busy||u.id===state.user.id" class="secondary" @click="demoLogin(u.id)">{{u.name}}</button></div></section></template>
  <template v-else-if="isAdmin&&!parent"><div class="empty"><ShieldCheck/><h2>부모 전용 화면입니다.</h2><RouterLink to="/today">오늘로 돌아가기</RouterLink></div></template>
  <template v-else-if="path==='/admin/reviews'"><div class="page-heading"><div><p class="eyebrow">A LITTLE ENCOURAGEMENT</p><h1>작은 실천, 확인해 주세요</h1><p class="muted">완료와 예외 신청 {{pending.length}}건이 기다리고 있어요.</p></div></div><section class="list-panel"><article v-for="m in state.data.missions.filter(m=>!['SUCCEEDED','FAILED','EXEMPT'].includes(m.status))" :key="m.id" class="review-row"><span class="avatar">{{names[m.userId]?.slice(0,1)}}</span><div class="grow"><span class="eyebrow">{{names[m.userId]}} · {{m.date}}</span><h3>{{m.title}}</h3><p>{{statusLabel[m.status]}} · {{m.note||m.description}}</p></div><div class="button-row"><button v-if="m.status==='SUBMITTED'" class="primary small" :disabled="busy" @click="decide(m,'SUCCEEDED')">+{{m.reward}}P 승인</button><button class="secondary small" @click="open('EXEMPT',m)">예외 승인</button><button class="text-button small" @click="open('FAILED',m)">미수행 확인</button></div></article><div v-if="!state.data.missions.some(m=>!['SUCCEEDED','FAILED','EXEMPT'].includes(m.status))" class="empty">확인할 미션이 없습니다.</div></section></template>
  <template v-else-if="path==='/admin/missions'"><div class="page-heading"><div><p class="eyebrow">FAMILY ROUTINES</p><h1>매일의 약속 만들기</h1><p class="muted">기본 미션은 가족의 모든 아이에게 배정됩니다.</p></div><button class="primary" @click="open('template')"><Plus :size="18"/>미션 추가</button></div><section class="list-panel"><article v-for="t in state.data.templates" :key="t.id" class="list-row"><div class="grow"><h3>{{t.title}} <span v-if="!t.active" class="badge">중지</span></h3><p>{{t.description}}</p><small>{{t.weekdays.split(',').map(d=>['일','월','화','수','목','금','토'][Number(d)]).join('·')}} · {{t.dueTime}} · +{{t.reward}}P / −{{t.penalty}}P</small></div><button class="secondary small" :disabled="busy" @click="run(()=>api(`/templates/${t.id}`,'PATCH',{active:!t.active}),t.active?'앞으로 새 미션을 생성하지 않습니다.':'미션을 다시 시작합니다.')">{{t.active?'중지':'다시 시작'}}</button></article></section><p class="muted footnote">중지해도 이미 생성된 미션과 포인트 기록은 유지됩니다.</p></template>
  <template v-else-if="path==='/admin/payments'"><div class="page-heading"><div><p class="eyebrow">SUNDAY SETTLEMENT</p><h1>노력이 용돈이 되는 시간</h1><p class="muted">승인 후 직접 송금하고, 지급 완료를 기록해 주세요.</p></div></div><div class="notice">주간 보너스 자동 정산은 운영 규칙 확정 후 연결합니다. 현재 잔액은 확정된 적립·차감만 반영합니다.</div><section class="list-panel"><article v-for="r in state.data.redemptions" :key="r.id" class="review-row"><span class="avatar">{{names[r.userId]?.slice(0,1)}}</span><div class="grow"><h3>{{names[r.userId]}} · {{(r.points*r.rate).toLocaleString()}}원</h3><p>{{r.points}}P · {{statusLabel[r.status]}} <span v-if="r.payingParentId">· 담당 {{names[r.payingParentId]}}</span></p></div><div class="button-row"><button v-if="r.status==='REQUESTED'" :disabled="busy" class="primary small" @click="payout(r,'approve')">승인</button><button v-if="['REQUESTED','APPROVED'].includes(r.status)" :disabled="busy" class="text-button small" @click="payout(r,'reject')">거절</button><button v-if="r.status==='APPROVED'" :disabled="busy" class="primary small" @click="payout(r,'start-payment')">지급 시작</button><button v-if="r.status==='PAYING'&&r.payingParentId===state.user.id" :disabled="busy" class="primary small" @click="payout(r,'mark-paid')">실제 지급 완료</button></div></article><div v-if="!state.data.redemptions.length" class="empty">아직 용돈 신청이 없습니다.</div></section></template>
 </div><div v-else class="empty"><p>가족 정보를 불러오지 못했습니다.</p><button class="primary" @click="run(load,'다시 불러왔습니다.')">다시 불러오기</button></div>
 </main><nav class="mobile-nav"><RouterLink v-for="n in nav" :key="n.to" :to="n.to" :class="{active:path===n.to}"><component :is="n.icon" :size="21"/><span>{{n.text}}</span></RouterLink><RouterLink v-if="parent" to="/admin/reviews" :class="{active:isAdmin}"><ShieldCheck :size="21"/><span>관리</span></RouterLink></nav>
</div>
<dialog ref="modalRef" v-if="dialog" class="modal" @cancel="dialog=''" aria-labelledby="dialog-title"><form @submit.prevent="save"><div class="section-heading"><h2 id="dialog-title">{{({exception:'오늘 미션 예외 신청',FAILED:'미수행 확인',EXEMPT:'예외 승인',withdraw:'용돈으로 바꾸기',event:'가족 일정 추가',template:'반복 미션 추가',invite:'가족 초대'})[dialog as 'event']}}</h2><button type="button" class="icon-button" aria-label="닫기" @click="dialog=''"><X/></button></div><template v-if="['exception','FAILED','EXEMPT'].includes(dialog)"><p>{{selectedMission?.title}}</p><label>사유<textarea v-model="reason" required maxlength="500" placeholder="가족이 이해할 수 있도록 알려주세요."></textarea></label></template><template v-if="dialog==='withdraw'"><p>인출 가능 {{available}}P · {{(available*100).toLocaleString()}}원</p><label>신청할 포인트<input v-model.number="points" type="number" min="1" :max="available" required></label><div class="conversion">{{(points*100).toLocaleString()}}원</div><p class="muted">실제 지급은 일요일 가족회의에서 진행해요.</p></template><template v-if="dialog==='event'||dialog==='template'"><label>이름<input v-model="formTitle" required maxlength="120" placeholder="함께 기억할 이름"></label><template v-if="dialog==='event'"><label>종류<select v-model="eventKind"><option value="EVENT">일회성 일정</option><option v-if="parent" value="ANNIVERSARY">매년 기념일 (양력)</option></select></label><label>날짜<input v-model="formDate" type="date" required></label></template><label>시간<input v-model="formTime" type="time" required></label><template v-if="dialog==='template'"><label>반복 요일<select v-model="weekdays"><option value="1,2,3,4,5">평일</option><option value="1,2,3,4,5,6,0">매일</option><option value="6,0">주말</option></select></label><div class="two-fields"><label>적립 P<input v-model.number="reward" type="number" min="0" max="10000" required></label><label>차감 P<input v-model.number="penalty" type="number" min="0" max="10000" required></label></div></template><label>{{dialog==='template'?'수행 기준':'준비물 · 메모'}}<textarea v-model="formNote" maxlength="500"></textarea></label></template><template v-if="dialog==='invite'"><label>이름<input v-model="inviteName" required maxlength="80"></label><label>Google 계정 이메일<input v-model="inviteEmail" type="email" required></label><label>가족 역할<select v-model="inviteRole"><option value="CHILD">아이</option><option value="PARENT">부모</option></select></label><div v-if="inviteToken" class="notice"><strong>초대 코드 · 24시간 유효</strong><textarea readonly :value="inviteToken" aria-label="생성된 초대 코드"></textarea><p>해당 가족에게 직접 전달해 주세요. 지정한 Google 계정에서만 사용할 수 있어요.</p></div></template><p class="error" v-if="state.error" role="alert">{{state.error}}</p><button class="primary wide" :disabled="busy">{{busy?'처리 중…':dialog==='invite'?'초대 코드 만들기':dialog==='withdraw'?'용돈 신청':'저장하기'}}</button></form></dialog><div v-if="state.toast" class="toast" role="status"><CircleCheck :size="19"/>{{state.toast}}</div>
</template>
