<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { api, load } from '../api';
import { CalendarDays, RefreshCw, Link2 } from 'lucide-vue-next';
interface Status {configured:boolean;connected:boolean;calendarId?:string|null;calendarName?:string|null;lastSyncedAt?:string|null;lastError?:string|null;}
const status=ref<Status|null>(null),choices=ref<{id:string;summary:string}[]>([]),selected=ref(''),busy=ref(false),error=ref(''),message=ref('');
async function refresh(){status.value=await api<Status>('/google-calendar/status');selected.value=status.value.calendarId||'';}
async function run(fn:()=>Promise<void>){busy.value=true;error.value='';message.value='';try{await fn();await refresh();await load();}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
function connect(){void run(async()=>{if(status.value?.connected&&!window.confirm('Google 계정을 다시 연결하면 가져온 일정을 지우고 캘린더를 다시 선택합니다. 계속할까요?'))return;const r=await api<{url:string}>('/google-calendar/authorize','POST',{});window.location.assign(r.url);});}
function list(){void run(async()=>{choices.value=await api('/google-calendar/calendars');});}
function select(){void run(async()=>{const r=await api<{count:number}>('/google-calendar/select','POST',{calendarId:selected.value});message.value=`${r.count}개 일정을 가져왔습니다.`;choices.value=[];});}
function sync(){void run(async()=>{const r=await api<{count:number}>('/google-calendar/sync','POST',{});message.value=`${r.count}개 일정으로 업데이트했습니다.`;});}
function disconnect(){if(!window.confirm('Google 연결을 해제할까요? 가져온 일정만 앱에서 지워집니다. Google 원본과 앱에서 만든 일정은 유지됩니다.'))return;void run(async()=>{await api('/google-calendar/connection','DELETE');choices.value=[];message.value='연결을 해제했습니다.';});}
onMounted(async()=>{const q=new URLSearchParams(location.search).get('google');if(q==='connected')message.value='Google 계정이 연결됐습니다. 가족이 함께 볼 캘린더를 선택해 주세요.';if(q==='error')error.value='Google 연결을 완료하지 못했습니다. 권한을 허용하고 다시 연결해 주세요.';try{await refresh();if(status.value?.connected&&!status.value.calendarId)choices.value=await api('/google-calendar/calendars');}catch(e){error.value=(e as Error).message;}});
</script>
<template><section class="google-calendar-panel"><div class="google-panel-heading"><div class="round-icon"><CalendarDays :size="21"/></div><div class="grow"><h2>Google 공유 캘린더</h2><p>{{status?.calendarName||'Google에서 관리하는 일정을 우리집에서도 확인해요.'}}</p></div><span class="badge">읽기 전용</span></div><p class="muted">지난 90일~앞으로 1년 · 15분마다 업데이트 · 시간은 한국 기준</p><p v-if="status?.lastSyncedAt" class="muted">마지막 가져오기: {{new Date(status.lastSyncedAt).toLocaleString('ko-KR')}}</p><p v-if="status&&!status.configured" class="notice">Google 캘린더 연결 설정을 준비 중입니다. 설정이 완료되면 부모 계정에서 연결할 수 있어요.</p><div class="button-row"><button v-if="status?.configured" class="secondary" :disabled="busy" @click="connect"><Link2 :size="17"/>{{status.connected?'Google 다시 연결':'Google 계정 연결'}}</button><button v-if="status?.connected" class="secondary" :disabled="busy" @click="list">캘린더 선택</button><button v-if="status?.calendarId" class="primary" :disabled="busy" @click="sync"><RefreshCw :size="17"/>{{busy?'가져오는 중…':'지금 가져오기'}}</button><button v-if="status?.connected" class="text-button" :disabled="busy" @click="disconnect">연결 해제</button></div><form v-if="choices.length" @submit.prevent="select" class="calendar-selection"><label>가족 전체에게 보여줄 캘린더<select v-model="selected" required><option value="" disabled>캘린더 선택</option><option v-for="c in choices" :key="c.id" :value="c.id">{{c.summary}}</option></select></label><p class="muted">선택한 캘린더의 제목·장소·설명이 모든 가족에게 표시됩니다. 공유할 캘린더인지 확인해 주세요.</p><button class="primary" :disabled="busy||!selected">이 캘린더 가져오기</button></form><p v-if="error||status?.lastError" class="error" role="alert">{{error||status?.lastError}}</p><p v-if="message" class="sync-message" role="status">{{message}}</p></section></template>
<style scoped>
.google-calendar-panel{padding:24px;background:#fff;border:1px solid var(--line);border-radius:16px;margin-bottom:25px}.google-panel-heading{display:flex;align-items:center;gap:13px;margin-bottom:13px}.google-panel-heading p{font-size:.85rem;color:var(--muted);margin-top:5px}.button-row{margin:16px 0 0}.google-calendar-panel>.notice,.google-calendar-panel>.error{margin:15px 0 0}.calendar-selection{border-top:1px solid var(--line);margin-top:20px;padding-top:5px}.calendar-selection button{margin-top:15px}.sync-message{color:var(--green);font-size:.88rem;margin-top:15px}.google-panel-heading .badge{white-space:nowrap}@media(max-width:760px){.google-calendar-panel{padding:18px}.google-panel-heading h2{font-size:1rem}}
</style>
